POST http://localhost:3000/reports
content-type: application/json

{
  "make": "Toyota",
  "model": "Corolla",
  "year": 2020,
  "mileage": 125000,
  "lng": 9.8,
  "lat": 36.5,
  "price": 15500
}

### Approve an existing report

PATCH  http://localhost:3000/reports/13
content-type: application/json

{
  "approved": true
}

### Get an estimate for an existing vehicle
GET http://localhost:3000/reports?make=Toyota&model=Corolla&lng=10&lat=36&mileage=123000 &year=2020
